language: node_js

sudo: required

services:
   - docker

node_js:
  - "iojs"

before_install:
   - gem install sass

script:
   - ./build.sh
   
after_success:
   -  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" tilos.hu:5555
   - ./docker.sh
   
notifications:
  webhooks: 
     urls: 
       - https://test.tilos.hu/notitest
